---
- hosts: all
  vars:
    XServiceName: lin_guider
    XServiceExec: "{{ ansible_user_dir }}/lin_guider_pack/lin_guider/lin_guider"
    XServiceDisplayNumber: "2"
    XServiceDisplayWidth: "645"
    XServiceDisplayHeight: "500"
  tasks:
  - name: Install prerequisites for building {{ XServiceName }}
    apt: name={{item}} state=installed update_cache=yes
    with_items:
      - libusb-1.0-0-dev
      - libqt4-dev
      - libftdi-dev
      - fxload
      - wget
      - bzip2
      - tar
      - build-essential
    become: true

  - name: Download {{ XServiceName }}
    command: wget http://downloads.sourceforge.net/project/linguider/4.1.0/lin_guider-4.1.0.tar.bz2 chdir={{ ansible_user_dir }} creates={{ ansible_user_dir }}/lin_guider-4.1.0.tar.bz2

  - name: Decompress {{ XServiceName }}
    command: bunzip2 lin_guider-4.1.0.tar.bz2 chdir={{ ansible_user_dir }} creates={{ ansible_user_dir }}/lin_guider-4.1.0.tar

  - name: Extract {{ XServiceName }}
    command: tar xf lin_guider-4.1.0.tar chdir={{ ansible_user_dir }} creates={{ ansible_user_dir }}/lin_guider_pack/lin_guider

  - name: Configure {{ XServiceName }}
    shell: ./configure chdir={{ ansible_user_dir }}/lin_guider_pack/lin_guider creates={{ ansible_user_dir }}/lin_guider_pack/lin_guider/Makefile

  - name: Build {{ XServiceName }}
    command: make -j {{ ansible_processor_vcpus }} chdir={{ ansible_user_dir }}/lin_guider_pack/lin_guider creates={{ XServiceExec }}
  
  - name: Install virtual graphical environment
    apt: name={{item}} state=installed
    with_items:
      - xvfb
      - x11vnc
    become: true

  - name: Create Virtual X frame buffer service for {{ XServiceName }}
    template: src=templates/Xvfb_xservice.service.j2 dest=/etc/systemd/system/Xvfb_{{ XServiceName }}.service mode=0644 owner=root group=root
    become: true

  - name: Create VNC service for {{ XServiceName }}
    template: src=templates/x11vnc_xservice.service.j2 dest=/etc/systemd/system/x11vnc_{{ XServiceName }}.service mode=0644 owner=root group=root
    become: true

  - name: Create {{ XServiceName }} service
    template: src=templates/xservice.service.j2 dest=/etc/systemd/system/{{ XServiceName }}.service mode=0644 owner=root group=root
    become: true

  - name: Reload system services
    command: systemctl daemon-reload
    become: true

  - name: Enable and start Virtual X frame buffer service for {{ XServiceName }}
    service: name=Xvfb_{{ XServiceName }} enabled=yes state=started
    become: true

  - name: Enable and start VNC service for {{ XServiceName }}
    service: name=x11vnc_{{ XServiceName }} enabled=yes state=started
    become: true

  - name: Enable and start {{ XServiceName }} service
    service: name={{ XServiceName }} enabled=yes state=started
    become: true
