---
- hosts: all
  vars:
    XServiceName: phd2
    XServiceExec: /usr/local/bin/phd2
    XServiceDisplayNumber: "1"
    XServiceDisplayWidth: "860"
    XServiceDisplayHeight: "660"
  tasks:
  - name: Install prerequisites for building {{ XServiceName }}
    apt: name={{item}} state=installed update_cache=yes
    with_items:
      - build-essential
      - git
      - cmake
      - pkg-config
      - libwxgtk3.0-dev
      - wx-common
      - wx3.0-i18n
      - libindi-dev
      - libnova-dev
      - zlib1g-dev
    become: true

  - name: Download {{ XServiceName }}
    git: >
      repo=https://github.com/OpenPHDGuiding/phd2.git
      dest={{ ansible_user_dir }}/phd2
      version=f8c684a0d94a38e924663561fafe1c0769e89351
      depth=1

  - name: Create tmp directory for {{ XServiceName }} compilation
    file: path={{ ansible_user_dir }}/phd2/tmp state=directory

  - name: Configure {{ XServiceName }}
    command: cmake .. chdir={{ ansible_user_dir }}/phd2/tmp creates={{ ansible_user_dir }}/phd2/tmp/Makefile

  - name: Build {{ XServiceName }}
    command: make -j {{ ansible_processor_vcpus }} chdir={{ ansible_user_dir }}/phd2/tmp creates={{ ansible_user_dir }}/phd2/tmp/phd2

  - name: Install {{ XServiceName }}
    command: make install chdir={{ ansible_user_dir }}/phd2/tmp creates={{ XServiceExec }}
    become: true

  - name: Install virtual graphical environment
    apt: name={{item}} state=installed
    with_items:
      - xvfb
      - x11vnc
      - websockify
    become: true

  - name: Create Virtual X frame buffer service for {{ XServiceName }}
    template: src=templates/Xvfb_xservice.service.j2 dest=/etc/systemd/system/Xvfb_{{ XServiceName }}.service mode=0644 owner=root group=root
    become: true

  - name: Create VNC service for {{ XServiceName }}
    template: src=templates/x11vnc_xservice.service.j2 dest=/etc/systemd/system/x11vnc_{{ XServiceName }}.service mode=0644 owner=root group=root
    become: true

  - name: Create websockify proxy service for x11vnc_{{ XServiceName }}
    template: src=templates/websockify_xservice.service.j2 dest=/etc/systemd/system/websockify_{{ XServiceName }}.service mode=0644 owner=root group=root
    become: true

  - name: Create {{ XServiceName}} service
    template: src=templates/xservice.service.j2 dest=/etc/systemd/system/{{ XServiceName }}.service mode=0644 owner=root group=root
    become: true

  - name: Reload system services
    command: systemctl daemon-reload
    become: true

  - name: Enable and start Virtual X frame buffer service for {{ XServiceName }}
    service: name=Xvfb_{{ XServiceName }} enabled=yes state=started
    become: true

  - name: Enable and start VNC service for {{ XServiceName }}
    service: name=x11vnc_{{ XServiceName }} enabled=yes state=started
    become: true

  - name: Enable and start websockify proxy service for x11vnc_{{ XServiceName }}
    service: name=websockify_{{ XServiceName }} enabled=yes state=started
    become: true

  - name: Enable and start {{ XServiceName }} service
    service: name={{ XServiceName }} enabled=yes state=started
    become: true
