---
- hosts: all
  vars:
    XServiceName: phd2
    XServiceExec: /usr/local/bin/phd2
    XServiceDisplayNumber: "1"
    XServiceDisplayWidth: "860"
    XServiceDisplayHeight: "660"
  tasks:

  - name: Enable and start Virtual X frame buffer service for {{ XServiceName }}
    service: name=Xvfb_{{ XServiceName }} enabled=yes state=started
    become: true

  - name: Enable and start VNC service for {{ XServiceName }}
    service: name=x11vnc_{{ XServiceName }} enabled=yes state=started
    become: true

  - name: Enable and start websockify proxy service for x11vnc_{{ XServiceName }}
    service: name=websockify_{{ XServiceName }} enabled=yes state=started
    become: true

  - name: Enable and start {{ XServiceName }} service
    service: name={{ XServiceName }} enabled=yes state=started
    become: true
